### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[34, 62, 51,  4],
       [49, 74, 32, 33],
       [ 5,  3, 56, 91],
       [42, 19, 97, 97],
       [82, 34, 92, 98],
       [32, 12, 83, 59]])

In [ ]:
np.sort(a)

array([ 2,  2,  8, 14, 40, 44, 44, 67, 79, 84, 84, 88, 89, 96, 99])

In [ ]:
np.sort(b) # here in this case sorting ahppens according to row wise, axis 1 is rowwise sorting, default is row wise

array([[ 4, 34, 51, 62],
       [32, 33, 49, 74],
       [ 3,  5, 56, 91],
       [19, 42, 97, 97],
       [34, 82, 92, 98],
       [12, 32, 59, 83]])

In [ ]:
np.sort(a)[::-1] # this is sorting in descending order

array([99, 96, 89, 88, 84, 84, 79, 67, 44, 44, 40, 14,  8,  2,  2])

In [ ]:
np.sort(b,axis=0) # axis 0 means column wise sorting

array([[ 5,  3, 32,  4],
       [32, 12, 51, 33],
       [34, 19, 56, 59],
       [42, 34, 83, 91],
       [49, 62, 92, 97],
       [82, 74, 97, 98]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 11,  53,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21, 200])

In [ ]:
b

array([[34, 62, 51,  4],
       [49, 74, 32, 33],
       [ 5,  3, 56, 91],
       [42, 19, 97, 97],
       [82, 34, 92, 98],
       [32, 12, 83, 59]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1) # want to add a new column, that means we need to add 1 to each row that is why axis 1 which refers to row
# b.shape[0] -> this gives number of rows and ,1 gives we are adding one column

array([[34., 62., 51.,  4.,  1.],
       [49., 74., 32., 33.,  1.],
       [ 5.,  3., 56., 91.,  1.],
       [42., 19., 97., 97.,  1.],
       [82., 34., 92., 98.,  1.],
       [32., 12., 83., 59.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[12.        , 52.        , 42.        ,  6.        ,  0.22006275],
       [29.        , 18.        , 47.        , 55.        ,  0.81740634],
       [61.        , 93.        , 83.        ,  9.        ,  0.89146072],
       [38.        , 63.        , 44.        , 85.        ,  0.84519124],
       [ 8.        , 87.        , 31.        , 72.        ,  0.24007274],
       [40.        , 71.        ,  2.        ,  7.        ,  0.48056374]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0) # these are similar to vstack and hstack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
# code
a.shape # here it is just 15 which is 1d

(15,)

In [ ]:
np.expand_dims(a,axis=0)

array([[ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89]])

In [ ]:
np.expand_dims(a,axis=0).shape # here it is 1,15 which is 1 row 15 columns

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[ 2],
       [88],
       [44],
       [84],
       [99],
       [44],
       [ 2],
       [67],
       [14],
       [79],
       [84],
       [40],
       [96],
       [ 8],
       [89]])

In [ ]:
np.expand_dims(a,axis=1).shape # here it is 15,1 which is 15 rows 1 column

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
# find all indices with value greater than 50
np.where(a>50) # this gives the index positions not the values

(array([ 1,  3,  4,  7,  9, 10, 12, 14]),)

In [ ]:
# replace all values > 50 with 0
# np.where(condition, value to insert for true, value to insert for false)
# -> when condition is true, put the value which is given in true place and when its false put value which is in false place
np.where(a>50,0,a)

array([ 2,  0, 44,  0,  0, 44,  2,  0, 14,  0,  0, 40,  0,  8,  0])

In [ ]:
np.where(a%2 == 0,0,a) # we are replacing even numbers with 0

array([ 0,  0,  0,  0, 99,  0,  0, 67,  0, 79,  0,  0,  0,  0, 89])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
np.argmax(a)

4

In [ ]:
b

array([[34, 62, 51,  4],
       [49, 74, 32, 33],
       [ 5,  3, 56, 91],
       [42, 19, 97, 97],
       [82, 34, 92, 98],
       [32, 12, 83, 59]])

In [ ]:
np.argmax(b,axis=0) # max numbers in columns 4,1,3,4 this is the output which means 82,74,97,98 values

array([4, 1, 3, 4])

In [ ]:
np.argmax(b,axis=1) # max numbers in rows 1,1,3,2,3,2 which corresponds to 62,74,91,97 this is the first 97,98,83

array([1, 1, 3, 2, 3, 2])

In [ ]:
# np.argmin
np.argmin(a)

0

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
np.cumsum(a)

array([  2,  90, 134, 218, 317, 361, 363, 430, 444, 523, 607, 647, 743,
       751, 840])

In [ ]:
b

array([[34, 62, 51,  4],
       [49, 74, 32, 33],
       [ 5,  3, 56, 91],
       [42, 19, 97, 97],
       [82, 34, 92, 98],
       [32, 12, 83, 59]])

In [ ]:
np.cumsum(b,axis=1) # this is adding row wise

array([[ 34,  96, 147, 151],
       [ 49, 123, 155, 188],
       [  5,   8,  64, 155],
       [ 42,  61, 158, 255],
       [ 82, 116, 208, 306],
       [ 32,  44, 127, 186]])

In [ ]:
np.cumsum(b) # when axis is not provides then it will be converted to 1d array and then adds cumulative sum

array([  34,   96,  147,  151,  200,  274,  306,  339,  344,  347,  403,
        494,  536,  555,  652,  749,  831,  865,  957, 1055, 1087, 1099,
       1182, 1241])

In [ ]:
# np.cumprod -> this is cumulative product
np.cumprod(a)

array([                   2,                  176,                 7744,
                     650496,             64399104,           2833560576,
                 5667121152,         379697117184,        5315759640576,
            419945011605504,    35275380974862336,  1411015238994493440,
        6330254427504508928, -4698196801092583424,  6135598398079762432])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
np.percentile(a,100) # 100 percentile would be the maximum number, here in this case its 99

99.0

In [ ]:
np.percentile(a,0) # 0 percentile would be the minimum number, here in this case its 2

2.0

In [ ]:
np.percentile(a,50) # 50 percentile would be the median, here in this case its 67

67.0

In [ ]:
np.median(a)

67.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])
# (array([3, 1, 0, 0, 3, 0, 1, 1, 4, 2]),
# array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))
# basically the output is there are 3 items(2,2,8) between 0 to 10 and there are 1 items(14) between 10 to 20 and there are 0 items between 20 to 30 and so on like that

(array([3, 1, 0, 0, 3, 0, 1, 1, 4, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
np.histogram(a,bins=[0,50,100])
# 7 items (2,44,44,2,14,40,8) betwen 0 to 50 and 8 items (88,84,99,67,79,84,96,89) between 50 to 100

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)
# this gives 4 values of correlation
#.     sal.  exp
# sal.  1.    0.25
# exp.   0.25  1


array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]
# we can search multiple items in one go using this function
a[np.isin(a,items)]

array([40])

In [ ]:
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False])

In [ ]:
np.isin(a, [10,20,30,40,50,60,70,88,90,100])

array([False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
np.flip(a)

array([89,  8, 96, 40, 84, 79, 14, 67,  2, 44, 99, 84, 44, 88,  2])

In [ ]:
b

array([[34, 62, 51,  4],
       [49, 74, 32, 33],
       [ 5,  3, 56, 91],
       [42, 19, 97, 97],
       [82, 34, 92, 98],
       [32, 12, 83, 59]])

In [ ]:
np.flip(b)

array([[59, 83, 12, 32],
       [98, 92, 34, 82],
       [97, 97, 19, 42],
       [91, 56,  3,  5],
       [33, 32, 74, 49],
       [ 4, 51, 62, 34]])

In [ ]:
np.flip(b,axis=1) # if axis is not specified then flipping happens along both the axis

array([[ 4, 51, 62, 34],
       [33, 32, 74, 49],
       [91, 56,  3,  5],
       [97, 97, 19, 42],
       [98, 92, 34, 82],
       [59, 83, 12, 32]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([ 2, 88, 44, 84, 99, 44,  2, 67, 14, 79, 84, 40, 96,  8, 89])

In [ ]:
np.put(a,[0,1],[110,530]) # we are replacing the indexes 0,1 elements with 110 and 530 and this got changed in the array, changes are permanent

In [ ]:
a

array([110, 530,  44,  84,  99,  44,   2,  67,  14,  79,  84,  40,  96,
         8,  89])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  44,  84,  99,  44,   2,  67,  14,  79,  84,  40,  96,
         8,  89])

In [ ]:
np.delete(a,[0,2,4]) # we are deleting 0,2,4 axis elements

array([530,  84,  44,   2,  67,  14,  79,  84,  40,  96,   8,  89])

In [ ]:
a

array([110, 530,  44,  84,  99,  44,   2,  67,  14,  79,  84,  40,  96,
         8,  89])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n) # m,n giving, means the elements that are not there in seoncd and present in first are returned herer it is 1,2

array([1, 2])

In [ ]:
np.setxor1d(m,n) # xor means not common values of both sets is returned

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

In [ ]:
np.in1d(m,1)

array([ True, False, False, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  44,  84,  99,  44,   2,  67,  14,  79,  84,  40,  96,
         8,  89])

In [ ]:
np.clip(a,a_min=25,a_max=75)
# values going out of our range 25 to 75 the higher values are replace by 75 and lower values are replaed by 25

array([75, 75, 44, 75, 75, 44, 25, 67, 25, 75, 75, 40, 75, 25, 75])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals